# Generated by Django 3.1.4 on 2020-12-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('p_conpra', models.FloatField(default=0.0)),
                ('p_venta', models.FloatField(default=0.0)),
                ('cantidad_vendidos', models.IntegerField(default=0)),
            ],
        ),
    ]
